// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminSession = `-- name: CreateAdminSession :one
INSERT INTO admin_sessions (admin_id, ip, user_agent, expires_at)
VALUES ($1, NULLIF($4::text, '')::inet, $2, $3)
RETURNING id
`

type CreateAdminSessionParams struct {
	AdminID   uuid.UUID
	UserAgent *string
	ExpiresAt pgtype.Timestamptz
	Ip        string
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAdminSession,
		arg.AdminID,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.Ip,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAdminSession = `-- name: DeleteAdminSession :exec
DELETE FROM admin_sessions WHERE id = $1
`

func (q *Queries) DeleteAdminSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdminSession, id)
	return err
}

const deleteExpiredAdminSessions = `-- name: DeleteExpiredAdminSessions :exec
DELETE FROM admin_sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredAdminSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAdminSessions)
	return err
}

const getAdminByLogin = `-- name: GetAdminByLogin :one
SELECT id, login, password_hash, telegram_id
FROM admin_users
WHERE login = $1
`

type GetAdminByLoginRow struct {
	ID           uuid.UUID
	Login        string
	PasswordHash string
	TelegramID   *int64
}

func (q *Queries) GetAdminByLogin(ctx context.Context, login string) (GetAdminByLoginRow, error) {
	row := q.db.QueryRow(ctx, getAdminByLogin, login)
	var i GetAdminByLoginRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.TelegramID,
	)
	return i, err
}

const getAdminByTelegramID = `-- name: GetAdminByTelegramID :one
SELECT id, login, password_hash, telegram_id
FROM admin_users
WHERE telegram_id = $1
`

type GetAdminByTelegramIDRow struct {
	ID           uuid.UUID
	Login        string
	PasswordHash string
	TelegramID   *int64
}

func (q *Queries) GetAdminByTelegramID(ctx context.Context, telegramID *int64) (GetAdminByTelegramIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminByTelegramID, telegramID)
	var i GetAdminByTelegramIDRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.TelegramID,
	)
	return i, err
}

const getAdminSession = `-- name: GetAdminSession :one
SELECT s.id, s.admin_id, s.expires_at, u.login
FROM admin_sessions s
JOIN admin_users u ON u.id = s.admin_id
WHERE s.id = $1 AND s.expires_at > now()
`

type GetAdminSessionRow struct {
	ID        uuid.UUID
	AdminID   uuid.UUID
	ExpiresAt pgtype.Timestamptz
	Login     string
}

func (q *Queries) GetAdminSession(ctx context.Context, id uuid.UUID) (GetAdminSessionRow, error) {
	row := q.db.QueryRow(ctx, getAdminSession, id)
	var i GetAdminSessionRow
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ExpiresAt,
		&i.Login,
	)
	return i, err
}

const setAdminLastLogin = `-- name: SetAdminLastLogin :exec
UPDATE admin_users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) SetAdminLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setAdminLastLogin, id)
	return err
}

const setAdminTelegramID = `-- name: SetAdminTelegramID :exec
UPDATE admin_users SET telegram_id = $2 WHERE login = $1
`

type SetAdminTelegramIDParams struct {
	Login      string
	TelegramID *int64
}

func (q *Queries) SetAdminTelegramID(ctx context.Context, arg SetAdminTelegramIDParams) error {
	_, err := q.db.Exec(ctx, setAdminTelegramID, arg.Login, arg.TelegramID)
	return err
}

const upsertAdminUser = `-- name: UpsertAdminUser :one
INSERT INTO admin_users (login, password_hash)
VALUES ($1, $2)
ON CONFLICT (login) DO UPDATE SET password_hash = EXCLUDED.password_hash
RETURNING id
`

type UpsertAdminUserParams struct {
	Login        string
	PasswordHash string
}

func (q *Queries) UpsertAdminUser(ctx context.Context, arg UpsertAdminUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertAdminUser, arg.Login, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
