// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: analytics.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (visitor_id, session_id, type, payload, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEventParams struct {
	VisitorID uuid.UUID
	SessionID uuid.UUID
	Type      string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.VisitorID,
		arg.SessionID,
		arg.Type,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const insertOrderPaidEvent = `-- name: InsertOrderPaidEvent :exec
INSERT INTO events (visitor_id, session_id, type, payload, created_at)
SELECT v.visitor_id, v.session_id, 'order_paid', $1::jsonb, now()
FROM visits v
JOIN orders o ON o.visitor_id = v.visitor_id
WHERE o.id = $2
ORDER BY v.created_at DESC
LIMIT 1
`

type InsertOrderPaidEventParams struct {
	Payload []byte
	OrderID uuid.UUID
}

// InsertOrderPaidEvent closes the funnel from the provider callback, which
// carries no cookies of its own. The event is filed against the last session the
// buyer was seen in, so it lines up with the earlier steps of the same visitor.
// An order whose visitor never landed a visit produces no event and is simply
// not part of the funnel.
func (q *Queries) InsertOrderPaidEvent(ctx context.Context, arg InsertOrderPaidEventParams) error {
	_, err := q.db.Exec(ctx, insertOrderPaidEvent, arg.Payload, arg.OrderID)
	return err
}

const insertVisit = `-- name: InsertVisit :exec
INSERT INTO visits (visitor_id, session_id, landing_path, referrer,
                    utm_source, utm_medium, utm_campaign, utm_content, utm_term,
                    user_agent, is_bot, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertVisitParams struct {
	VisitorID   uuid.UUID
	SessionID   uuid.UUID
	LandingPath string
	Referrer    *string
	UtmSource   *string
	UtmMedium   *string
	UtmCampaign *string
	UtmContent  *string
	UtmTerm     *string
	UserAgent   *string
	IsBot       bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertVisit(ctx context.Context, arg InsertVisitParams) error {
	_, err := q.db.Exec(ctx, insertVisit,
		arg.VisitorID,
		arg.SessionID,
		arg.LandingPath,
		arg.Referrer,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
		arg.UtmContent,
		arg.UtmTerm,
		arg.UserAgent,
		arg.IsBot,
		arg.CreatedAt,
	)
	return err
}
