// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cart.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cartExists = `-- name: CartExists :one
SELECT EXISTS (SELECT 1 FROM carts WHERE id = $1)
`

func (q *Queries) CartExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, cartExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (visitor_id)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateCart(ctx context.Context, visitorID pgtype.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCart, visitorID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteCartItem = `-- name: DeleteCartItem :execrows
DELETE FROM cart_items WHERE id = $2 AND cart_id = $1
`

type DeleteCartItemParams struct {
	CartID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCartItem, arg.CartID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCartItemByVariant = `-- name: GetCartItemByVariant :one
SELECT id, qty FROM cart_items WHERE cart_id = $1 AND variant_id = $2
`

type GetCartItemByVariantParams struct {
	CartID    uuid.UUID
	VariantID uuid.UUID
}

type GetCartItemByVariantRow struct {
	ID  uuid.UUID
	Qty int32
}

func (q *Queries) GetCartItemByVariant(ctx context.Context, arg GetCartItemByVariantParams) (GetCartItemByVariantRow, error) {
	row := q.db.QueryRow(ctx, getCartItemByVariant, arg.CartID, arg.VariantID)
	var i GetCartItemByVariantRow
	err := row.Scan(&i.ID, &i.Qty)
	return i, err
}

const insertCartItem = `-- name: InsertCartItem :exec
INSERT INTO cart_items (cart_id, variant_id, qty)
VALUES ($1, $2, $3)
ON CONFLICT (cart_id, variant_id) DO UPDATE SET qty = EXCLUDED.qty
`

type InsertCartItemParams struct {
	CartID    uuid.UUID
	VariantID uuid.UUID
	Qty       int32
}

func (q *Queries) InsertCartItem(ctx context.Context, arg InsertCartItemParams) error {
	_, err := q.db.Exec(ctx, insertCartItem, arg.CartID, arg.VariantID, arg.Qty)
	return err
}

const listCartItems = `-- name: ListCartItems :many
SELECT ci.id, ci.variant_id, ci.qty,
       v.size, v.stock, v.reserved,
       p.slug, p.title, p.price_cents, p.currency, p.image_front
FROM cart_items ci
JOIN product_variants v ON v.id = ci.variant_id
JOIN products p ON p.id = v.product_id
WHERE ci.cart_id = $1
ORDER BY p.sort_order, array_position(ARRAY['S', 'M', 'L', 'XL', 'XXL']::text[], v.size)
`

type ListCartItemsRow struct {
	ID         uuid.UUID
	VariantID  uuid.UUID
	Qty        int32
	Size       string
	Stock      int32
	Reserved   int32
	Slug       string
	Title      string
	PriceCents int64
	Currency   string
	ImageFront string
}

func (q *Queries) ListCartItems(ctx context.Context, cartID uuid.UUID) ([]ListCartItemsRow, error) {
	rows, err := q.db.Query(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCartItemsRow{}
	for rows.Next() {
		var i ListCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.Qty,
			&i.Size,
			&i.Stock,
			&i.Reserved,
			&i.Slug,
			&i.Title,
			&i.PriceCents,
			&i.Currency,
			&i.ImageFront,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchCart = `-- name: TouchCart :exec
UPDATE carts SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchCart(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchCart, id)
	return err
}

const updateCartItemQty = `-- name: UpdateCartItemQty :execrows
UPDATE cart_items SET qty = $3 WHERE id = $2 AND cart_id = $1
`

type UpdateCartItemQtyParams struct {
	CartID uuid.UUID
	ID     uuid.UUID
	Qty    int32
}

func (q *Queries) UpdateCartItemQty(ctx context.Context, arg UpdateCartItemQtyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCartItemQty, arg.CartID, arg.ID, arg.Qty)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
