// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: catalog.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, slug, title, description, price_cents, currency, image_front, image_back, is_active, sort_order
FROM products
WHERE slug = $1 AND is_active = true
`

type GetProductBySlugRow struct {
	ID          uuid.UUID
	Slug        string
	Title       string
	Description string
	PriceCents  int64
	Currency    string
	ImageFront  string
	ImageBack   string
	IsActive    bool
	SortOrder   int32
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.ImageFront,
		&i.ImageBack,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const getVariantWithProduct = `-- name: GetVariantWithProduct :one
SELECT v.id, v.product_id, v.size, v.sku, v.stock, v.reserved,
       p.slug, p.title, p.description, p.price_cents, p.currency,
       p.image_front, p.image_back, p.is_active, p.sort_order
FROM product_variants v
JOIN products p ON p.id = v.product_id
WHERE v.id = $1
`

type GetVariantWithProductRow struct {
	ID          uuid.UUID
	ProductID   uuid.UUID
	Size        string
	Sku         string
	Stock       int32
	Reserved    int32
	Slug        string
	Title       string
	Description string
	PriceCents  int64
	Currency    string
	ImageFront  string
	ImageBack   string
	IsActive    bool
	SortOrder   int32
}

func (q *Queries) GetVariantWithProduct(ctx context.Context, id uuid.UUID) (GetVariantWithProductRow, error) {
	row := q.db.QueryRow(ctx, getVariantWithProduct, id)
	var i GetVariantWithProductRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Size,
		&i.Sku,
		&i.Stock,
		&i.Reserved,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.ImageFront,
		&i.ImageBack,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, slug, title, description, price_cents, currency, image_front, image_back, is_active, sort_order
FROM products
WHERE is_active = true
ORDER BY sort_order, created_at
`

type ListActiveProductsRow struct {
	ID          uuid.UUID
	Slug        string
	Title       string
	Description string
	PriceCents  int64
	Currency    string
	ImageFront  string
	ImageBack   string
	IsActive    bool
	SortOrder   int32
}

func (q *Queries) ListActiveProducts(ctx context.Context) ([]ListActiveProductsRow, error) {
	rows, err := q.db.Query(ctx, listActiveProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProductsRow{}
	for rows.Next() {
		var i ListActiveProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.PriceCents,
			&i.Currency,
			&i.ImageFront,
			&i.ImageBack,
			&i.IsActive,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProductIDs = `-- name: ListVariantsByProductIDs :many
SELECT id, product_id, size, sku, stock, reserved
FROM product_variants
WHERE product_id = ANY ($1::uuid[])
ORDER BY product_id, array_position(ARRAY['S', 'M', 'L', 'XL', 'XXL']::text[], size)
`

func (q *Queries) ListVariantsByProductIDs(ctx context.Context, productIds []uuid.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProductIDs, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Size,
			&i.Sku,
			&i.Stock,
			&i.Reserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
