// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: catalogadmin.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getVariantProductID = `-- name: GetVariantProductID :one
SELECT product_id
FROM product_variants
WHERE id = $1
`

func (q *Queries) GetVariantProductID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getVariantProductID, id)
	var product_id uuid.UUID
	err := row.Scan(&product_id)
	return product_id, err
}

const insertPriceChange = `-- name: InsertPriceChange :exec
INSERT INTO price_history (product_id, old_price_cents, new_price_cents, changed_by, reason)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPriceChangeParams struct {
	ProductID     uuid.UUID
	OldPriceCents int64
	NewPriceCents int64
	ChangedBy     pgtype.UUID
	Reason        *string
}

func (q *Queries) InsertPriceChange(ctx context.Context, arg InsertPriceChangeParams) error {
	_, err := q.db.Exec(ctx, insertPriceChange,
		arg.ProductID,
		arg.OldPriceCents,
		arg.NewPriceCents,
		arg.ChangedBy,
		arg.Reason,
	)
	return err
}

const listPriceHistory = `-- name: ListPriceHistory :many
SELECT h.old_price_cents, h.new_price_cents, h.reason, h.created_at, u.login, p.currency
FROM price_history h
JOIN products p ON p.id = h.product_id
LEFT JOIN admin_users u ON u.id = h.changed_by
WHERE h.product_id = $1
ORDER BY h.created_at DESC
LIMIT $2
`

type ListPriceHistoryParams struct {
	ProductID uuid.UUID
	Limit     int32
}

type ListPriceHistoryRow struct {
	OldPriceCents int64
	NewPriceCents int64
	Reason        *string
	CreatedAt     pgtype.Timestamptz
	Login         *string
	Currency      string
}

func (q *Queries) ListPriceHistory(ctx context.Context, arg ListPriceHistoryParams) ([]ListPriceHistoryRow, error) {
	rows, err := q.db.Query(ctx, listPriceHistory, arg.ProductID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriceHistoryRow{}
	for rows.Next() {
		var i ListPriceHistoryRow
		if err := rows.Scan(
			&i.OldPriceCents,
			&i.NewPriceCents,
			&i.Reason,
			&i.CreatedAt,
			&i.Login,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsForAdmin = `-- name: ListProductsForAdmin :many

SELECT id, slug, title, description, price_cents, currency,
       image_front, image_back, is_active, sort_order
FROM products
ORDER BY sort_order, created_at
`

type ListProductsForAdminRow struct {
	ID          uuid.UUID
	Slug        string
	Title       string
	Description string
	PriceCents  int64
	Currency    string
	ImageFront  string
	ImageBack   string
	IsActive    bool
	SortOrder   int32
}

// Queries behind the admin product page (tech.md §8.3).
// The panel sees deactivated models too: they still carry stock and history.
func (q *Queries) ListProductsForAdmin(ctx context.Context) ([]ListProductsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listProductsForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsForAdminRow{}
	for rows.Next() {
		var i ListProductsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.PriceCents,
			&i.Currency,
			&i.ImageFront,
			&i.ImageBack,
			&i.IsActive,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProductForPrice = `-- name: LockProductForPrice :one
SELECT price_cents, currency
FROM products
WHERE id = $1
FOR UPDATE
`

type LockProductForPriceRow struct {
	PriceCents int64
	Currency   string
}

func (q *Queries) LockProductForPrice(ctx context.Context, id uuid.UUID) (LockProductForPriceRow, error) {
	row := q.db.QueryRow(ctx, lockProductForPrice, id)
	var i LockProductForPriceRow
	err := row.Scan(&i.PriceCents, &i.Currency)
	return i, err
}

const setProductPrice = `-- name: SetProductPrice :execrows
UPDATE products
SET price_cents = $2, updated_at = now()
WHERE id = $1
`

type SetProductPriceParams struct {
	ID         uuid.UUID
	PriceCents int64
}

func (q *Queries) SetProductPrice(ctx context.Context, arg SetProductPriceParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProductPrice, arg.ID, arg.PriceCents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setVariantStock = `-- name: SetVariantStock :execrows
UPDATE product_variants
SET stock = $1::int
WHERE id = $2 AND $1::int >= reserved
`

type SetVariantStockParams struct {
	Stock     int32
	VariantID uuid.UUID
}

// The stock never lands below what is already reserved, so a size with units in
// a live checkout cannot be sold twice: no matching row means the edit is
// refused rather than clamped (tech.md §4).
func (q *Queries) SetVariantStock(ctx context.Context, arg SetVariantStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVariantStock, arg.Stock, arg.VariantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
