// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminSession struct {
	ID        uuid.UUID
	AdminID   uuid.UUID
	Ip        *netip.Addr
	UserAgent *string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type AdminUser struct {
	ID           uuid.UUID
	Login        string
	PasswordHash string
	TelegramID   *int64
	CreatedAt    pgtype.Timestamptz
	LastLoginAt  pgtype.Timestamptz
}

type Cart struct {
	ID        uuid.UUID
	VisitorID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CartItem struct {
	ID        uuid.UUID
	CartID    uuid.UUID
	VariantID uuid.UUID
	Qty       int32
}

type Event struct {
	ID        int64
	VisitorID uuid.UUID
	SessionID uuid.UUID
	Type      string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

type Notification struct {
	ID            uuid.UUID
	OrderID       pgtype.UUID
	ChatID        int64
	Kind          string
	Payload       []byte
	DedupKey      string
	Status        string
	Attempts      int32
	NextAttemptAt pgtype.Timestamptz
	LastError     *string
	CreatedAt     pgtype.Timestamptz
	SentAt        pgtype.Timestamptz
}

type Order struct {
	ID              uuid.UUID
	Number          string
	PublicToken     string
	TgLinkCode      string
	Status          string
	SubtotalCents   int64
	ShippingCents   int64
	TotalCents      int64
	Currency        string
	CustomerName    string
	CustomerContact string
	ShippingAddress string
	Comment         *string
	VisitorID       pgtype.UUID
	FirstTouch      []byte
	LastTouch       []byte
	ExpiresAt       pgtype.Timestamptz
	PaidAt          pgtype.Timestamptz
	ShippedAt       pgtype.Timestamptz
	CancelledAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type OrderItem struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	VariantID      uuid.UUID
	ProductTitle   string
	Size           string
	UnitPriceCents int64
	Qty            int32
}

type Payment struct {
	ID                uuid.UUID
	OrderID           uuid.UUID
	Provider          string
	ProviderPaymentID string
	InvoiceUrl        *string
	PayCurrency       *string
	PayAmount         pgtype.Numeric
	ActuallyPaid      pgtype.Numeric
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PaymentEvent struct {
	ID             uuid.UUID
	PaymentID      pgtype.UUID
	ProviderStatus string
	Payload        []byte
	SignatureOk    bool
	DedupKey       string
	ReceivedAt     pgtype.Timestamptz
}

type PriceHistory struct {
	ID            uuid.UUID
	ProductID     uuid.UUID
	OldPriceCents int64
	NewPriceCents int64
	ChangedBy     pgtype.UUID
	Reason        *string
	CreatedAt     pgtype.Timestamptz
}

type Product struct {
	ID          uuid.UUID
	Slug        string
	Title       string
	Description string
	PriceCents  int64
	Currency    string
	ImageFront  string
	ImageBack   string
	IsActive    bool
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProductVariant struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Size      string
	Sku       string
	Stock     int32
	Reserved  int32
}

type Setting struct {
	Key       string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}

type TelegramLink struct {
	ID       uuid.UUID
	OrderID  uuid.UUID
	ChatID   int64
	Username *string
	LinkedAt pgtype.Timestamptz
}

type TelegramUpdate struct {
	UpdateID   int64
	ReceivedAt pgtype.Timestamptz
}

type Visit struct {
	ID          uuid.UUID
	VisitorID   uuid.UUID
	SessionID   uuid.UUID
	LandingPath string
	Referrer    *string
	UtmSource   *string
	UtmMedium   *string
	UtmCampaign *string
	UtmContent  *string
	UtmTerm     *string
	UserAgent   *string
	IsBot       bool
	CreatedAt   pgtype.Timestamptz
}
