// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notify.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueNotifications = `-- name: ClaimDueNotifications :many
SELECT id, order_id, chat_id, kind, payload, attempts
FROM notifications
WHERE status = 'pending' AND next_attempt_at <= $1
ORDER BY next_attempt_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimDueNotificationsParams struct {
	NextAttemptAt pgtype.Timestamptz
	Limit         int32
}

type ClaimDueNotificationsRow struct {
	ID       uuid.UUID
	OrderID  pgtype.UUID
	ChatID   int64
	Kind     string
	Payload  []byte
	Attempts int32
}

func (q *Queries) ClaimDueNotifications(ctx context.Context, arg ClaimDueNotificationsParams) ([]ClaimDueNotificationsRow, error) {
	rows, err := q.db.Query(ctx, claimDueNotifications, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueNotificationsRow{}
	for rows.Next() {
		var i ClaimDueNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ChatID,
			&i.Kind,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countNotificationsByStatus = `-- name: CountNotificationsByStatus :one
SELECT count(*) FROM notifications WHERE status = $1
`

func (q *Queries) CountNotificationsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueNotification = `-- name: EnqueueNotification :execrows
INSERT INTO notifications (order_id, chat_id, kind, payload, dedup_key, status, next_attempt_at)
VALUES ($1, $2, $3, $4, $5, 'pending', now())
ON CONFLICT (dedup_key) DO NOTHING
`

type EnqueueNotificationParams struct {
	OrderID  pgtype.UUID
	ChatID   int64
	Kind     string
	Payload  []byte
	DedupKey string
}

func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueNotification,
		arg.OrderID,
		arg.ChatID,
		arg.Kind,
		arg.Payload,
		arg.DedupKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notifications
SET status = 'failed', attempts = attempts + 1, last_error = $2
WHERE id = $1
`

type MarkNotificationFailedParams struct {
	ID        uuid.UUID
	LastError *string
}

func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.ID, arg.LastError)
	return err
}

const markNotificationRetry = `-- name: MarkNotificationRetry :exec
UPDATE notifications
SET attempts = attempts + 1, next_attempt_at = $2, last_error = $3
WHERE id = $1
`

type MarkNotificationRetryParams struct {
	ID            uuid.UUID
	NextAttemptAt pgtype.Timestamptz
	LastError     *string
}

func (q *Queries) MarkNotificationRetry(ctx context.Context, arg MarkNotificationRetryParams) error {
	_, err := q.db.Exec(ctx, markNotificationRetry, arg.ID, arg.NextAttemptAt, arg.LastError)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notifications
SET status = 'sent', sent_at = $2, attempts = attempts + 1, last_error = NULL
WHERE id = $1
`

type MarkNotificationSentParams struct {
	ID     uuid.UUID
	SentAt pgtype.Timestamptz
}

func (q *Queries) MarkNotificationSent(ctx context.Context, arg MarkNotificationSentParams) error {
	_, err := q.db.Exec(ctx, markNotificationSent, arg.ID, arg.SentAt)
	return err
}
