// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const commitVariantStock = `-- name: CommitVariantStock :execrows
UPDATE product_variants
SET stock = stock - LEAST(stock, $1::int),
    reserved = reserved - LEAST(reserved, $1::int)
WHERE id = $2
`

type CommitVariantStockParams struct {
	Qty       int32
	VariantID uuid.UUID
}

func (q *Queries) CommitVariantStock(ctx context.Context, arg CommitVariantStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, commitVariantStock, arg.Qty, arg.VariantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestInvoiceURL = `-- name: GetLatestInvoiceURL :one
SELECT invoice_url
FROM payments
WHERE order_id = $1 AND invoice_url IS NOT NULL
ORDER BY created_at DESC
LIMIT 1
`

// A provider callback opens its own payment row without an invoice url, so the
// link the buyer can still use is the latest row that actually carries one.
func (q *Queries) GetLatestInvoiceURL(ctx context.Context, orderID uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getLatestInvoiceURL, orderID)
	var invoice_url *string
	err := row.Scan(&invoice_url)
	return invoice_url, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, number, public_token, tg_link_code, status,
       subtotal_cents, shipping_cents, total_cents, currency,
       customer_name, customer_contact, shipping_address, comment,
       expires_at, paid_at, created_at
FROM orders
WHERE number = $1
`

type GetOrderByNumberRow struct {
	ID              uuid.UUID
	Number          string
	PublicToken     string
	TgLinkCode      string
	Status          string
	SubtotalCents   int64
	ShippingCents   int64
	TotalCents      int64
	Currency        string
	CustomerName    string
	CustomerContact string
	ShippingAddress string
	Comment         *string
	ExpiresAt       pgtype.Timestamptz
	PaidAt          pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetOrderByNumber(ctx context.Context, number string) (GetOrderByNumberRow, error) {
	row := q.db.QueryRow(ctx, getOrderByNumber, number)
	var i GetOrderByNumberRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.PublicToken,
		&i.TgLinkCode,
		&i.Status,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.TotalCents,
		&i.Currency,
		&i.CustomerName,
		&i.CustomerContact,
		&i.ShippingAddress,
		&i.Comment,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByPublicToken = `-- name: GetOrderByPublicToken :one
SELECT id, number, public_token, tg_link_code, status,
       subtotal_cents, shipping_cents, total_cents, currency,
       customer_name, customer_contact, shipping_address, comment,
       expires_at, paid_at, created_at
FROM orders
WHERE public_token = $1
`

type GetOrderByPublicTokenRow struct {
	ID              uuid.UUID
	Number          string
	PublicToken     string
	TgLinkCode      string
	Status          string
	SubtotalCents   int64
	ShippingCents   int64
	TotalCents      int64
	Currency        string
	CustomerName    string
	CustomerContact string
	ShippingAddress string
	Comment         *string
	ExpiresAt       pgtype.Timestamptz
	PaidAt          pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetOrderByPublicToken(ctx context.Context, publicToken string) (GetOrderByPublicTokenRow, error) {
	row := q.db.QueryRow(ctx, getOrderByPublicToken, publicToken)
	var i GetOrderByPublicTokenRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.PublicToken,
		&i.TgLinkCode,
		&i.Status,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.TotalCents,
		&i.Currency,
		&i.CustomerName,
		&i.CustomerContact,
		&i.ShippingAddress,
		&i.Comment,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertCheckoutOrder = `-- name: InsertCheckoutOrder :one
INSERT INTO orders (number, public_token, tg_link_code, status,
                    subtotal_cents, shipping_cents, total_cents, currency,
                    customer_name, customer_contact, shipping_address, comment,
                    visitor_id, first_touch, last_touch, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, created_at
`

type InsertCheckoutOrderParams struct {
	Number          string
	PublicToken     string
	TgLinkCode      string
	Status          string
	SubtotalCents   int64
	ShippingCents   int64
	TotalCents      int64
	Currency        string
	CustomerName    string
	CustomerContact string
	ShippingAddress string
	Comment         *string
	VisitorID       pgtype.UUID
	FirstTouch      []byte
	LastTouch       []byte
	ExpiresAt       pgtype.Timestamptz
}

type InsertCheckoutOrderRow struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertCheckoutOrder(ctx context.Context, arg InsertCheckoutOrderParams) (InsertCheckoutOrderRow, error) {
	row := q.db.QueryRow(ctx, insertCheckoutOrder,
		arg.Number,
		arg.PublicToken,
		arg.TgLinkCode,
		arg.Status,
		arg.SubtotalCents,
		arg.ShippingCents,
		arg.TotalCents,
		arg.Currency,
		arg.CustomerName,
		arg.CustomerContact,
		arg.ShippingAddress,
		arg.Comment,
		arg.VisitorID,
		arg.FirstTouch,
		arg.LastTouch,
		arg.ExpiresAt,
	)
	var i InsertCheckoutOrderRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listDueOrders = `-- name: ListDueOrders :many
SELECT id, number
FROM orders
WHERE status = 'awaiting_payment'
  AND expires_at IS NOT NULL
  AND expires_at < $1
ORDER BY expires_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListDueOrdersParams struct {
	ExpiresAt pgtype.Timestamptz
	Limit     int32
}

type ListDueOrdersRow struct {
	ID     uuid.UUID
	Number string
}

func (q *Queries) ListDueOrders(ctx context.Context, arg ListDueOrdersParams) ([]ListDueOrdersRow, error) {
	rows, err := q.db.Query(ctx, listDueOrders, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueOrdersRow{}
	for rows.Next() {
		var i ListDueOrdersRow
		if err := rows.Scan(&i.ID, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrder = `-- name: ListOrderItemsByOrder :many
SELECT variant_id, product_title, size, unit_price_cents, qty
FROM order_items
WHERE order_id = $1
ORDER BY id
`

type ListOrderItemsByOrderRow struct {
	VariantID      uuid.UUID
	ProductTitle   string
	Size           string
	UnitPriceCents int64
	Qty            int32
}

func (q *Queries) ListOrderItemsByOrder(ctx context.Context, orderID uuid.UUID) ([]ListOrderItemsByOrderRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsByOrderRow{}
	for rows.Next() {
		var i ListOrderItemsByOrderRow
		if err := rows.Scan(
			&i.VariantID,
			&i.ProductTitle,
			&i.Size,
			&i.UnitPriceCents,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrderByID = `-- name: LockOrderByID :one
SELECT id, number, status
FROM orders
WHERE id = $1
FOR UPDATE
`

type LockOrderByIDRow struct {
	ID     uuid.UUID
	Number string
	Status string
}

func (q *Queries) LockOrderByID(ctx context.Context, id uuid.UUID) (LockOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, lockOrderByID, id)
	var i LockOrderByIDRow
	err := row.Scan(&i.ID, &i.Number, &i.Status)
	return i, err
}

const lockOrderByNumber = `-- name: LockOrderByNumber :one
SELECT id, status
FROM orders
WHERE number = $1
FOR UPDATE
`

type LockOrderByNumberRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) LockOrderByNumber(ctx context.Context, number string) (LockOrderByNumberRow, error) {
	row := q.db.QueryRow(ctx, lockOrderByNumber, number)
	var i LockOrderByNumberRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const releaseVariant = `-- name: ReleaseVariant :execrows
UPDATE product_variants
SET reserved = reserved - LEAST(reserved, $1::int)
WHERE id = $2
`

type ReleaseVariantParams struct {
	Qty       int32
	VariantID uuid.UUID
}

// The releases clamp at zero so that replaying a release can never push the
// columns below their check constraints: stock - reserved >= 0 always holds.
func (q *Queries) ReleaseVariant(ctx context.Context, arg ReleaseVariantParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseVariant, arg.Qty, arg.VariantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveVariant = `-- name: ReserveVariant :execrows
UPDATE product_variants
SET reserved = reserved + $1::int
WHERE id = $2 AND stock - reserved >= $1::int
`

type ReserveVariantParams struct {
	Qty       int32
	VariantID uuid.UUID
}

func (q *Queries) ReserveVariant(ctx context.Context, arg ReserveVariantParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveVariant, arg.Qty, arg.VariantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOrderStatus = `-- name: SetOrderStatus :execrows
UPDATE orders
SET status = $2,
    updated_at = now(),
    paid_at = CASE WHEN $2 = 'paid' THEN now() ELSE paid_at END,
    cancelled_at = CASE WHEN $2 = 'cancelled' THEN now() ELSE cancelled_at END
WHERE id = $1 AND status = $3
`

type SetOrderStatusParams struct {
	ID       uuid.UUID
	Status   string
	Status_2 string
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOrderStatus, arg.ID, arg.Status, arg.Status_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
