// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orderadmin.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminOrder = `-- name: GetAdminOrder :one
SELECT id, number, public_token, tg_link_code, status,
       subtotal_cents, shipping_cents, total_cents, currency,
       customer_name, customer_contact, shipping_address, comment,
       first_touch, last_touch,
       expires_at, paid_at, shipped_at, cancelled_at, created_at
FROM orders
WHERE id = $1
`

type GetAdminOrderRow struct {
	ID              uuid.UUID
	Number          string
	PublicToken     string
	TgLinkCode      string
	Status          string
	SubtotalCents   int64
	ShippingCents   int64
	TotalCents      int64
	Currency        string
	CustomerName    string
	CustomerContact string
	ShippingAddress string
	Comment         *string
	FirstTouch      []byte
	LastTouch       []byte
	ExpiresAt       pgtype.Timestamptz
	PaidAt          pgtype.Timestamptz
	ShippedAt       pgtype.Timestamptz
	CancelledAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetAdminOrder(ctx context.Context, id uuid.UUID) (GetAdminOrderRow, error) {
	row := q.db.QueryRow(ctx, getAdminOrder, id)
	var i GetAdminOrderRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.PublicToken,
		&i.TgLinkCode,
		&i.Status,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.TotalCents,
		&i.Currency,
		&i.CustomerName,
		&i.CustomerContact,
		&i.ShippingAddress,
		&i.Comment,
		&i.FirstTouch,
		&i.LastTouch,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminOrders = `-- name: ListAdminOrders :many

SELECT o.id, o.number, o.status, o.total_cents, o.currency,
       o.customer_name, o.customer_contact, o.created_at, o.paid_at,
       (SELECT coalesce(sum(i.qty), 0) FROM order_items i WHERE i.order_id = o.id)::int AS units,
       count(*) OVER ()::bigint AS total_rows
FROM orders o
WHERE ($1::text IS NULL OR o.status = $1::text)
  AND ($2::timestamptz IS NULL OR o.created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR o.created_at < $3::timestamptz)
  AND ($4::text IS NULL OR o.number ILIKE '%' || $4::text || '%')
  AND ($5::uuid IS NULL OR EXISTS (
        SELECT 1
        FROM order_items i
        JOIN product_variants v ON v.id = i.variant_id
        WHERE i.order_id = o.id AND v.product_id = $5::uuid))
ORDER BY o.created_at DESC
LIMIT $7::int OFFSET $6::int
`

type ListAdminOrdersParams struct {
	Status      *string
	CreatedFrom pgtype.Timestamptz
	CreatedTo   pgtype.Timestamptz
	Number      *string
	ProductID   pgtype.UUID
	PageOffset  int32
	PageSize    int32
}

type ListAdminOrdersRow struct {
	ID              uuid.UUID
	Number          string
	Status          string
	TotalCents      int64
	Currency        string
	CustomerName    string
	CustomerContact string
	CreatedAt       pgtype.Timestamptz
	PaidAt          pgtype.Timestamptz
	Units           int32
	TotalRows       int64
}

// Queries behind the admin order list and card (tech.md §8.4).
// Every filter is optional and applied only when its argument is not null, so
// one query serves the whole filter bar. The total travels in a window count:
// the page and the number of pages come out of a single round trip, and the
// WHERE clause exists exactly once.
func (q *Queries) ListAdminOrders(ctx context.Context, arg ListAdminOrdersParams) ([]ListAdminOrdersRow, error) {
	rows, err := q.db.Query(ctx, listAdminOrders,
		arg.Status,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Number,
		arg.ProductID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminOrdersRow{}
	for rows.Next() {
		var i ListAdminOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.TotalCents,
			&i.Currency,
			&i.CustomerName,
			&i.CustomerContact,
			&i.CreatedAt,
			&i.PaidAt,
			&i.Units,
			&i.TotalRows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentEventsByOrder = `-- name: ListPaymentEventsByOrder :many
SELECT e.provider_status, e.signature_ok, e.received_at,
       p.provider_payment_id, p.pay_currency, p.pay_amount, p.actually_paid
FROM payment_events e
JOIN payments p ON p.id = e.payment_id
WHERE p.order_id = $1
ORDER BY e.received_at DESC
`

type ListPaymentEventsByOrderRow struct {
	ProviderStatus    string
	SignatureOk       bool
	ReceivedAt        pgtype.Timestamptz
	ProviderPaymentID string
	PayCurrency       *string
	PayAmount         pgtype.Numeric
	ActuallyPaid      pgtype.Numeric
}

// The raw provider log of one order, newest first (tech.md §8.4). Events whose
// signature failed never reach a payment row and so never reach a card.
func (q *Queries) ListPaymentEventsByOrder(ctx context.Context, orderID uuid.UUID) ([]ListPaymentEventsByOrderRow, error) {
	rows, err := q.db.Query(ctx, listPaymentEventsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentEventsByOrderRow{}
	for rows.Next() {
		var i ListPaymentEventsByOrderRow
		if err := rows.Scan(
			&i.ProviderStatus,
			&i.SignatureOk,
			&i.ReceivedAt,
			&i.ProviderPaymentID,
			&i.PayCurrency,
			&i.PayAmount,
			&i.ActuallyPaid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTelegramLinksByOrder = `-- name: ListTelegramLinksByOrder :many
SELECT chat_id, username, linked_at
FROM telegram_links
WHERE order_id = $1
ORDER BY linked_at
`

type ListTelegramLinksByOrderRow struct {
	ChatID   int64
	Username *string
	LinkedAt pgtype.Timestamptz
}

func (q *Queries) ListTelegramLinksByOrder(ctx context.Context, orderID uuid.UUID) ([]ListTelegramLinksByOrderRow, error) {
	rows, err := q.db.Query(ctx, listTelegramLinksByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTelegramLinksByOrderRow{}
	for rows.Next() {
		var i ListTelegramLinksByOrderRow
		if err := rows.Scan(&i.ChatID, &i.Username, &i.LinkedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
