// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPaymentByProviderID = `-- name: GetPaymentByProviderID :one
SELECT id, order_id, invoice_url, status
FROM payments
WHERE provider = $1 AND provider_payment_id = $2
`

type GetPaymentByProviderIDParams struct {
	Provider          string
	ProviderPaymentID string
}

type GetPaymentByProviderIDRow struct {
	ID         uuid.UUID
	OrderID    uuid.UUID
	InvoiceUrl *string
	Status     string
}

func (q *Queries) GetPaymentByProviderID(ctx context.Context, arg GetPaymentByProviderIDParams) (GetPaymentByProviderIDRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderID, arg.Provider, arg.ProviderPaymentID)
	var i GetPaymentByProviderIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceUrl,
		&i.Status,
	)
	return i, err
}

const insertPaymentEvent = `-- name: InsertPaymentEvent :execrows
INSERT INTO payment_events (payment_id, provider_status, payload, signature_ok, dedup_key)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (dedup_key) DO NOTHING
`

type InsertPaymentEventParams struct {
	PaymentID      pgtype.UUID
	ProviderStatus string
	Payload        []byte
	SignatureOk    bool
	DedupKey       string
}

func (q *Queries) InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPaymentEvent,
		arg.PaymentID,
		arg.ProviderStatus,
		arg.Payload,
		arg.SignatureOk,
		arg.DedupKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPayment = `-- name: UpsertPayment :one
INSERT INTO payments (order_id, provider, provider_payment_id, invoice_url,
                      pay_currency, pay_amount, actually_paid, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (provider, provider_payment_id) DO UPDATE
SET status        = EXCLUDED.status,
    invoice_url   = COALESCE(EXCLUDED.invoice_url, payments.invoice_url),
    pay_currency  = COALESCE(EXCLUDED.pay_currency, payments.pay_currency),
    pay_amount    = COALESCE(EXCLUDED.pay_amount, payments.pay_amount),
    actually_paid = COALESCE(EXCLUDED.actually_paid, payments.actually_paid),
    updated_at    = now()
RETURNING id
`

type UpsertPaymentParams struct {
	OrderID           uuid.UUID
	Provider          string
	ProviderPaymentID string
	InvoiceUrl        *string
	PayCurrency       *string
	PayAmount         pgtype.Numeric
	ActuallyPaid      pgtype.Numeric
	Status            string
}

func (q *Queries) UpsertPayment(ctx context.Context, arg UpsertPaymentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPayment,
		arg.OrderID,
		arg.Provider,
		arg.ProviderPaymentID,
		arg.InvoiceUrl,
		arg.PayCurrency,
		arg.PayAmount,
		arg.ActuallyPaid,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
