// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seed.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (number, public_token, tg_link_code, status,
                    subtotal_cents, shipping_cents, total_cents, currency,
                    customer_name, customer_contact, shipping_address,
                    visitor_id, first_touch, last_touch, paid_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $16)
RETURNING id
`

type InsertOrderParams struct {
	Number          string
	PublicToken     string
	TgLinkCode      string
	Status          string
	SubtotalCents   int64
	ShippingCents   int64
	TotalCents      int64
	Currency        string
	CustomerName    string
	CustomerContact string
	ShippingAddress string
	VisitorID       pgtype.UUID
	FirstTouch      []byte
	LastTouch       []byte
	PaidAt          pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.Number,
		arg.PublicToken,
		arg.TgLinkCode,
		arg.Status,
		arg.SubtotalCents,
		arg.ShippingCents,
		arg.TotalCents,
		arg.Currency,
		arg.CustomerName,
		arg.CustomerContact,
		arg.ShippingAddress,
		arg.VisitorID,
		arg.FirstTouch,
		arg.LastTouch,
		arg.PaidAt,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertOrderItem = `-- name: InsertOrderItem :exec
INSERT INTO order_items (order_id, variant_id, product_title, size, unit_price_cents, qty)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOrderItemParams struct {
	OrderID        uuid.UUID
	VariantID      uuid.UUID
	ProductTitle   string
	Size           string
	UnitPriceCents int64
	Qty            int32
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem,
		arg.OrderID,
		arg.VariantID,
		arg.ProductTitle,
		arg.Size,
		arg.UnitPriceCents,
		arg.Qty,
	)
	return err
}

const insertPriceHistory = `-- name: InsertPriceHistory :exec
INSERT INTO price_history (product_id, old_price_cents, new_price_cents, reason, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPriceHistoryParams struct {
	ProductID     uuid.UUID
	OldPriceCents int64
	NewPriceCents int64
	Reason        *string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) InsertPriceHistory(ctx context.Context, arg InsertPriceHistoryParams) error {
	_, err := q.db.Exec(ctx, insertPriceHistory,
		arg.ProductID,
		arg.OldPriceCents,
		arg.NewPriceCents,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (slug, title, description, price_cents, currency,
                      image_front, image_back, is_active, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, true, $8)
RETURNING id
`

type InsertProductParams struct {
	Slug        string
	Title       string
	Description string
	PriceCents  int64
	Currency    string
	ImageFront  string
	ImageBack   string
	SortOrder   int32
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.PriceCents,
		arg.Currency,
		arg.ImageFront,
		arg.ImageBack,
		arg.SortOrder,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertVariant = `-- name: InsertVariant :exec
INSERT INTO product_variants (product_id, size, sku, stock, reserved)
VALUES ($1, $2, $3, $4, 0)
`

type InsertVariantParams struct {
	ProductID uuid.UUID
	Size      string
	Sku       string
	Stock     int32
}

func (q *Queries) InsertVariant(ctx context.Context, arg InsertVariantParams) error {
	_, err := q.db.Exec(ctx, insertVariant,
		arg.ProductID,
		arg.Size,
		arg.Sku,
		arg.Stock,
	)
	return err
}

const listVariantIDs = `-- name: ListVariantIDs :many
SELECT v.id, v.product_id, v.size, p.title, p.price_cents
FROM product_variants v
JOIN products p ON p.id = v.product_id
ORDER BY p.sort_order, v.size
`

type ListVariantIDsRow struct {
	ID         uuid.UUID
	ProductID  uuid.UUID
	Size       string
	Title      string
	PriceCents int64
}

func (q *Queries) ListVariantIDs(ctx context.Context) ([]ListVariantIDsRow, error) {
	rows, err := q.db.Query(ctx, listVariantIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantIDsRow{}
	for rows.Next() {
		var i ListVariantIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Size,
			&i.Title,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeDemoData = `-- name: PurgeDemoData :exec
TRUNCATE payment_events, payments, order_items, orders, cart_items, carts,
         notifications, telegram_links, telegram_updates, events, visits,
         price_history, product_variants, products RESTART IDENTITY CASCADE
`

func (q *Queries) PurgeDemoData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeDemoData)
	return err
}
