// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: telegram.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getOrderByLinkCode = `-- name: GetOrderByLinkCode :one
SELECT id, number, status
FROM orders
WHERE tg_link_code = $1
`

type GetOrderByLinkCodeRow struct {
	ID     uuid.UUID
	Number string
	Status string
}

func (q *Queries) GetOrderByLinkCode(ctx context.Context, tgLinkCode string) (GetOrderByLinkCodeRow, error) {
	row := q.db.QueryRow(ctx, getOrderByLinkCode, tgLinkCode)
	var i GetOrderByLinkCodeRow
	err := row.Scan(&i.ID, &i.Number, &i.Status)
	return i, err
}

const insertTelegramLink = `-- name: InsertTelegramLink :execrows
INSERT INTO telegram_links (order_id, chat_id, username)
VALUES ($1, $2, $3)
ON CONFLICT (order_id, chat_id) DO NOTHING
`

type InsertTelegramLinkParams struct {
	OrderID  uuid.UUID
	ChatID   int64
	Username *string
}

func (q *Queries) InsertTelegramLink(ctx context.Context, arg InsertTelegramLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTelegramLink, arg.OrderID, arg.ChatID, arg.Username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTelegramUpdate = `-- name: InsertTelegramUpdate :execrows
INSERT INTO telegram_updates (update_id)
VALUES ($1)
ON CONFLICT (update_id) DO NOTHING
`

// The primary key is the whole deduplication rule: a redelivered update touches
// no row and reports zero, so the handler can leave without any side effect.
func (q *Queries) InsertTelegramUpdate(ctx context.Context, updateID int64) (int64, error) {
	result, err := q.db.Exec(ctx, insertTelegramUpdate, updateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOrdersByChat = `-- name: ListOrdersByChat :many
SELECT o.id, o.number, o.status
FROM orders o
JOIN telegram_links l ON l.order_id = o.id
WHERE l.chat_id = $1
ORDER BY o.created_at DESC
`

type ListOrdersByChatRow struct {
	ID     uuid.UUID
	Number string
	Status string
}

func (q *Queries) ListOrdersByChat(ctx context.Context, chatID int64) ([]ListOrdersByChatRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersByChatRow{}
	for rows.Next() {
		var i ListOrdersByChatRow
		if err := rows.Scan(&i.ID, &i.Number, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
